---
# tasks file for ansible_setup

- name: Create a log file for ansible
  file:
    path: "{{ ansible_log_path }}"
    state: touch
    mode: 0644
    owner: "{{ ansible_env.USER }}"
    group: wheel
  become: true
  tags: always
